// ignore_for_file: constant_identifier_names
// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-realtime-models.mjs from shared-event-schema/socket-events.schema.json

class GeneratedSocketEvents {
  GeneratedSocketEvents._();

  static const String ChatMessageCreatedV1 = 'chat:message.created.v1';
  static const String ChatSuggestionCreatedV1 = 'chat:suggestion.created.v1';
  static const String ChatMessageReceiptUpdatedV1 =
      'chat:message.receipt.updated.v1';
  static const String AuctionBidPlacedV1 = 'auction:bid.placed.v1';
  static const String AdminFlagUpdatedV1 = 'admin:flag.updated.v1';
  static const String AdminDisputeDecidedV1 = 'admin:dispute.decided.v1';
  static const String ChatMessage = 'chat:message';
  static const String ChatReceipt = 'chat:receipt';
  static const String AuctionBid = 'auction:bid';

  static const Set<String> canonical = <String>{
    'chat:message.created.v1',
    'chat:suggestion.created.v1',
    'chat:message.receipt.updated.v1',
    'auction:bid.placed.v1',
    'admin:flag.updated.v1',
    'admin:dispute.decided.v1',
  };

  static const Set<String> aliases = <String>{
    'chat:message',
    'chat:receipt',
    'auction:bid',
  };

  static const Set<String> all = <String>{
    'chat:message.created.v1',
    'chat:suggestion.created.v1',
    'chat:message.receipt.updated.v1',
    'auction:bid.placed.v1',
    'admin:flag.updated.v1',
    'admin:dispute.decided.v1',
    'chat:message',
    'chat:receipt',
    'auction:bid',
  };
}

class GeneratedSocketEventEnvelope {
  final String type;
  final Map<String, dynamic> payload;

  const GeneratedSocketEventEnvelope({
    required this.type,
    required this.payload,
  });

  bool get isKnownType => GeneratedSocketEvents.all.contains(type);
}
